const articles = [
    {
      id: 0,
      name: "World of Warcraft",
      url: "./assets/img/world of warcraft.jpg",
      price: 35,
      promo: true,
      qte: 4,
      description:
        "World of Warcraft best MMORPG",
    },
    {
      id: 1,
      name: "Diablo III",
      url: "./assets/img/diablo.jpg",
      price: 25,
      promo: false,
      qte: 7,
      description: "Best game of all times.Verry cheap",
    },
    {
      id: 2,
      name: "StarCraft II",
      url: "./assets/img/starcraft.jpg",
      price: 15,
      promo: true,
      qte: 15,
      description: "Best game of all times.Verry cheap",
    },
    {
      id: 3,
      name: "Final Fantasy XIV",
      url: "./assets/img/finalfantasy.jpg",
      price: 50,
      promo: true,
      qte: 5,
      description: "Best game of all times.Verry cheap",
    },
    {
      id: 4,
      name: "Dota II",
      url: "./assets/img/dota.jpg",
      price: 50,
      promo: true,
      qte: 10,
      description: "Best game of all times.Verry cheap",
    },
    {
      id: 5,
      name: "Heroes III",
      url: "./assets/img/heroes.jpg",
      price: 50,
      promo: true,
      qte: 5,
      description: "Best game of all times.Verry cheap",
    },
    {
      id: 6,
      name: "Civilization IV",
      url: "./assets/img/civ.jpg",
      price: 10,
      promo: true,
      qte: 50,
      description: "Best game of all times.Verry cheap",
    },
    {
      id: 7,
      name: "Civilization IV",
      url: "./assets/img/civ.jpg",
      price: 40,
      promo: true,
      qte: 10,
      description: "Best game of all times.Verry cheap",
    },
  ];
  export default articles;